//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bahare_zorufchi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public long ID { get; set; }
        public Nullable<long> kalaID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Text { get; set; }
        public bool IsAccepted { get; set; }
    
        public virtual kala kala { get; set; }
    }
}
