//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bahare_zorufchi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kala
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kala()
        {
            this.comments = new HashSet<comment>();
        }
    
        public long ID { get; set; }
        public int categoryID { get; set; }
        public string Name { get; set; }
        public string Producer { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public int Original_Price { get; set; }
        public int Discount_Price { get; set; }
        public bool IsAvailable { get; set; }
        public Nullable<int> like { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
    }
}
